#!/bin/bash

source _env.sh

source _setmodel.sh $1

echo "Mount Point::"
echo "$model_local_fullpath:$model_rel_path"

export model_name=$1

mkdir -p $model_local_fullpath
echo "bash $train_script $model_name"

$docker_exec run -it  -v $(pwd):$container_workdir \
        -v $lib_root:$docker_lib_root \
        -v  $model_local_fullpath:/$model_rel_path \
        -e DISPLAY=$DISPLAY \
        $container_tag \
	bash $train_script $model_name
