FROM jgwill/gix-adaptive-style-transfer:prod-cpu

#@STCGoal Mastery of the EntryPointing :: run the work in one command

# CHG to CPU
COPY _env.sh .


ENTRYPOINT ["/bin/bash","/work/v03-test-train-210108.sh"
